config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  resource :forecast, only: [:show]

  # Defines the root path route ("/")
  root "forecasts#new"
end

app/models/address.rb
class Address
  include ActiveModel::API

  attr_accessor :street, :city, :state, :country, :postal_code

  validates_presence_of :postal_code

  def full_address
    [street, city, [state, postal_code].compact.join(" "), country].compact.join(", ")
  end

  def lat_long
    @latitude, @longitude = OpenMateo.geocode(full_address)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
class Forecast
  include ActiveModel::API

  attr_accessor :latitude, :longitude,
    :timezone, :timezone_abbreviation, :elevation,
    :temp_units, :wind_units, :cached

  attr_reader :daily, :current

  class << self
    def retrieve(address)
      OpenMateo.forecast(address)
    end
  end

  def cached?
    cached == true
  end

  def daily=(value)
    @daily = value
    
    @daily.each { |day| day.forecast = self }
  end

  def current=(value)
    @current = value

    @current.forecast = self
  end
end

app/models/forecast_day.rb
class ForecastDay
  include ActiveModel::API

  attr_accessor :date, :min, :max,
    :temperature_2m, :precipitation, :relative_humidity_2m,
    :apparent_temperature, :wind_gusts_10m, :wind_speed_10m, :forecast

  delegate :temp_units, :wind_units, :cached?, to: :@forecast
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  def new
    @address = Address.new
  end

  def show
    @address = Address.new(address_params)

    unless @address.valid?
      @error = @address.errors.full_messages.join("\n")
    end

    @forecast = Forecast.retrieve(@address) unless @error.present?
  rescue OpenMateo::GeocodeError, OpenMateo::ForecastError => error
    @error = error.message
  end

  private

  def address_params
    params.require(:address).permit(:street, :city, :state, :country, :postal_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forecasts/new.html.erb
<div class="flex flex-row h-100 gap-12">
  <div class="bg-gray-100 p-3">
    <%= form_with url: forecast_path, method: :get, scope: @address, data: { turbo_frame: "forecast" } do |form| %>
      <%= form.label :postal_code %>
      <%= form.text_field :postal_code, class: "bg-white rounded" %>

      <%= form.submit "Retrieve Forecast", class: "middle none center mr-3 rounded-lg bg-pink-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-pink-500/20 transition-all hover:shadow-lg hover:shadow-pink-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
    <% end %>
  </div>

  <%= turbo_frame_tag "forecast" do %>
  <% end %>
</div>

app/views/forecasts/show.html.erb
<%= turbo_frame_tag "forecast" do %>
  <% unless @error.present? %>
    <% @presenter = ForecastDayPresenter.new(@forecast.current) %>

    <h2 class="font-bold text-2x1">Current conditions:</h2>
    
    <dl>
      <%= tag.dt "Temp", class: "font-bold" %>
      <%= tag.dd @presenter.temp, class: "ps-4" %>

      <%= tag.dt "Feels like", class: "font-bold" %>
      <%= tag.dd @presenter.feels_like, class: "ps-4" %>

      <%= tag.dt "Wind speed", class: "font-bold" %>
      <%= tag.dd @presenter.wind_speed, class: "ps-4" %>
    </dl>

    <h3 class="text-2x1">Upcoming:</h3>
    <table class="border-separate border-spacing-2 border border-gray-400 dark:border-gray-500">
      <thead>
        <tr>
          <td>Date</td>
          <td>Low</td>
          <td>High</td>
        </tr>
      </thead>
      <tbody>
        <% @forecast.daily.each do |future_forecast_day| %>
          <tr>
            <% @day_presenter = ForecastDayPresenter.new(future_forecast_day) %>
            <%= tag.td @day_presenter.day %>
            <%= tag.td @day_presenter.min %>
            <%= tag.td @day_presenter.max %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= tag.p @presenter.cache_note %>
  <% else %>
    <%= tag.p @error, class: "red" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Apple Forecasts" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>